# shellcheck shell=bash
# GENERATED by scripts/gen-ops-wiring.py from apps/bothy-collector/reads.toml - DO NOT EDIT. Run `just ops-wiring`.
#
# Sourced by scripts/gen-collector-token.sh, which defines
#   probe <expect yes|no> <verb> <resource[/subresource]> <namespace | -A | - >
# A subresource is written `pods/exec` here and goes to can-i as
# --subresource=exec: `can-i get pods/exec` reads TYPE/NAME, so it asks about a
# pod NAMED exec and answers for `get pods` (found 2026-09-17 in the other two
# scripts, where it printed yes for a grant that did not exist).
#
# Every read reads.toml declares must be yes; every refusal must be no.

# ── granted: list, and only list ──
probe yes list namespaces -
probe yes list services -A
probe yes list deployments.apps -A
probe yes list ingresses.networking.k8s.io -A
probe yes list routes.route.openshift.io -A
# ── refused ──
probe no list secrets -A
probe no get secrets thales-pre-prod
probe no get secrets bothy
probe no list configmaps -A
probe no get deployments.apps thales-pre-prod
probe no get namespaces -
probe no watch deployments.apps -A
probe no list pods -A
probe no get pods/log thales-pre-prod
probe no list nodes -
probe no list persistentvolumeclaims -A
probe no list events -A
probe no list serviceaccounts -A
probe no list roles.rbac.authorization.k8s.io -A
probe no list clusterroles.rbac.authorization.k8s.io -
probe no create pods/exec thales-pre-prod
probe no get pods/exec thales-pre-prod
probe no create pods/attach thales-pre-prod
probe no create pods/portforward thales-pre-prod
probe no create serviceaccounts/token bothy
probe no impersonate serviceaccounts bothy
probe no escalate clusterroles.rbac.authorization.k8s.io -
probe no bind clusterroles.rbac.authorization.k8s.io -
probe no create deployments.apps thales-pre-prod
probe no update deployments.apps thales-pre-prod
probe no patch deployments.apps thales-pre-prod
probe no delete deployments.apps thales-pre-prod
probe no patch deployments.apps kube-system
probe no delete pods kube-system
probe no create jobs.batch kube-system
probe no deletecollection pods -A
probe no create namespaces -
probe no delete namespaces -
