# GENERATED by scripts/gen-ops-wiring.py from apps/bothy-ops/catalog.toml - DO NOT EDIT. Run `just ops-wiring`.
#
# Sourced by scripts/gen-kube-token.sh, which defines
#   probe <expect yes|no> <verb> <resource[/name]> <namespace or - for cluster scope> [--<subresource>]
# `configmaps/thales` is a NAME (resourceNames). A subresource is never written
# `pods/exec`: can-i reads that as a pod named exec, and answers for `get pods`.
# Every verb the generated Role grants must be yes; the refusals must be no.

# ── thales-dev: granted ──
probe yes get configmaps/thales thales-dev
probe yes patch configmaps/thales thales-dev
probe yes list events thales-dev
probe yes list limitranges thales-dev
probe yes list persistentvolumeclaims thales-dev
probe yes get pods thales-dev
probe yes list pods thales-dev
probe yes delete pods thales-dev
probe yes list resourcequotas thales-dev
probe yes list services thales-dev
probe yes get deployments.apps thales-dev
probe yes list deployments.apps thales-dev
probe yes patch deployments.apps thales-dev
probe yes get replicasets.apps thales-dev
probe yes list replicasets.apps thales-dev
probe yes get jobs.batch thales-dev
probe yes list jobs.batch thales-dev
probe yes delete jobs.batch thales-dev
probe yes create jobs.batch thales-dev
probe yes list ingresses.networking.k8s.io thales-dev
probe yes list networkpolicies.networking.k8s.io thales-dev
probe yes list routes.route.openshift.io thales-dev
probe yes get pods thales-dev --log
probe yes get deployments.apps thales-dev --scale
probe yes patch deployments.apps thales-dev --scale
# ── thales-dev: refused ──
probe no create pods thales-dev --exec
probe no get pods thales-dev --exec
probe no create pods thales-dev --attach
probe no get pods thales-dev --attach
probe no create pods thales-dev --portforward
probe no get pods thales-dev --portforward
probe no get secrets thales-dev
probe no list secrets thales-dev
probe no get secrets/thales thales-dev
probe no watch pods thales-dev
probe no watch events thales-dev
probe no create pods thales-dev
probe no create deployments.apps thales-dev
probe no update deployments.apps thales-dev
probe no deletecollection pods thales-dev
probe no get configmaps/kube-root-ca.crt thales-dev
probe no list configmaps thales-dev
probe no escalate roles.rbac.authorization.k8s.io thales-dev
probe no bind roles.rbac.authorization.k8s.io thales-dev
probe no create rolebindings.rbac.authorization.k8s.io thales-dev
probe no impersonate serviceaccounts thales-dev
probe no create serviceaccounts thales-dev --token
# ── thales-pre-prod: granted ──
probe yes get configmaps/thales thales-pre-prod
probe yes patch configmaps/thales thales-pre-prod
probe yes list events thales-pre-prod
probe yes list limitranges thales-pre-prod
probe yes list persistentvolumeclaims thales-pre-prod
probe yes get pods thales-pre-prod
probe yes list pods thales-pre-prod
probe yes delete pods thales-pre-prod
probe yes list resourcequotas thales-pre-prod
probe yes list services thales-pre-prod
probe yes get deployments.apps thales-pre-prod
probe yes list deployments.apps thales-pre-prod
probe yes patch deployments.apps thales-pre-prod
probe yes get replicasets.apps thales-pre-prod
probe yes list replicasets.apps thales-pre-prod
probe yes get jobs.batch thales-pre-prod
probe yes list jobs.batch thales-pre-prod
probe yes delete jobs.batch thales-pre-prod
probe yes create jobs.batch thales-pre-prod
probe yes list ingresses.networking.k8s.io thales-pre-prod
probe yes list networkpolicies.networking.k8s.io thales-pre-prod
probe yes list routes.route.openshift.io thales-pre-prod
probe yes get pods thales-pre-prod --log
probe yes get deployments.apps thales-pre-prod --scale
probe yes patch deployments.apps thales-pre-prod --scale
# ── thales-pre-prod: refused ──
probe no create pods thales-pre-prod --exec
probe no get pods thales-pre-prod --exec
probe no create pods thales-pre-prod --attach
probe no get pods thales-pre-prod --attach
probe no create pods thales-pre-prod --portforward
probe no get pods thales-pre-prod --portforward
probe no get secrets thales-pre-prod
probe no list secrets thales-pre-prod
probe no get secrets/thales thales-pre-prod
probe no watch pods thales-pre-prod
probe no watch events thales-pre-prod
probe no create pods thales-pre-prod
probe no create deployments.apps thales-pre-prod
probe no update deployments.apps thales-pre-prod
probe no deletecollection pods thales-pre-prod
probe no get configmaps/kube-root-ca.crt thales-pre-prod
probe no list configmaps thales-pre-prod
probe no escalate roles.rbac.authorization.k8s.io thales-pre-prod
probe no bind roles.rbac.authorization.k8s.io thales-pre-prod
probe no create rolebindings.rbac.authorization.k8s.io thales-pre-prod
probe no impersonate serviceaccounts thales-pre-prod
probe no create serviceaccounts thales-pre-prod --token
# ── outside the two namespaces, and cluster scope ──
probe no create namespaces -
probe no delete namespaces -
probe no get secrets bothy
probe no list pods kube-system
probe no patch deployments.apps thales
probe no create jobs.batch kube-system
probe no list nodes -
