#!/usr/bin/env bash
# Generate edge/dynamic/bothy-prom.yml - the portal's read-only metrics data
# plane. The backend is VictoriaMetrics since 2026-09-17 (monitoring/compose.yml);
# it serves the Prometheus query API, so the routed paths did not change - only
# the upstream URL did. Rollback: METRICS_UPSTREAM=http://prometheus:9090.
#
# WHY A GENERATOR AND NOT A CHECKED-IN FILE: Prometheus grew basic auth on
# 2026-08-08 when the SSO was parked (monitoring/prometheus-web.yml, gitignored).
# The portal is a browser app and cannot hold a credential, so the edge injects
# the Authorization header on its behalf. That header IS the credential, so the
# file it lives in must never be committed - hence this script writes it from
# ~/stacks/.env and .gitignore excludes the output.
#
# Re-run after changing DEV_LOGIN_USER / DEV_LOGIN_PASSWORD. Traefik's file
# provider watches ./dynamic, so no restart is needed - but see the bind-mount
# caveat in edge/compose.yml if you have just switched branches.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/edge/dynamic/bothy-prom.yml"

[ -f "$root/.env" ] || { echo "no $root/.env - nothing to read credentials from" >&2; exit 1; }
set -a; . "$root/.env"; set +a
: "${DEV_LOGIN_USER:?set DEV_LOGIN_USER in .env}"
: "${DEV_LOGIN_PASSWORD:?set DEV_LOGIN_PASSWORD in .env}"

basic="$(printf '%s:%s' "$DEV_LOGIN_USER" "$DEV_LOGIN_PASSWORD" | base64 -w0)"
upstream="${METRICS_UPSTREAM:-http://victoriametrics:8428}"

cat > "$out" <<YAML
# GENERATED by scripts/gen-bothy-prom-route.sh - DO NOT COMMIT, DO NOT EDIT.
# Contains a basic-auth credential for Prometheus. Regenerate with:
#   just bothy-prom-route
#
# The portal's time-series source. Same model as bothy-api.yml: same-origin
# under /-/api/*, exact Path() only, read-only.
#
# ── SECURITY ───────────────────────────────────────────────────────────────
# Exactly TWO paths are routed, both of which only READ:
#   /-/api/prom/query        → instant vector
#   /-/api/prom/query_range  → range vector (the graphs)
# Never widen to PathPrefix. VictoriaMetrics on the same port also serves
# /api/v1/admin/tsdb/delete_series, /-/reload, /snapshot/* and - unlike a stock
# Prometheus - its WRITE endpoints: /api/v1/import and /api/v1/write accept data.
# A PathPrefix here would hand all of that to anything on the tailnet.
#
# What this does expose, unauthenticated, to the tailnet: every metric and every
# label value - container names, image names, mount paths, host interface names.
# The same categories /-/api/docker/containers/json already publishes. NOT Env,
# and no credential: the Authorization header is added here, on the way in, and
# is never visible to the browser.
http:
  routers:
    bothy-api-prom:
      rule: >-
        Path(\`/-/api/prom/query\`)
        || Path(\`/-/api/prom/query_range\`)
      entryPoints: [web]
      priority: 100
      middlewares: [bothy-api-prom-rewrite, bothy-api-prom-auth]
      service: bothy-prometheus

  middlewares:
    # /-/api/prom/query_range -> /api/v1/query_range
    bothy-api-prom-rewrite:
      replacePathRegex:
        regex: "^/-/api/prom/(.*)"
        replacement: "/api/v1/\$1"

    # The credential the browser must not hold.
    bothy-api-prom-auth:
      headers:
        customRequestHeaders:
          Authorization: "Basic $basic"

  services:
    bothy-prometheus:
      loadBalancer:
        servers:
          - url: "$upstream"
YAML

chmod 600 "$out"
echo "wrote $out (mode 600, gitignored)"
