#!/usr/bin/env bash
# Generate edge/dynamic/portal-prom.yml — the portal's read-only Prometheus
# data plane.
#
# WHY A GENERATOR AND NOT A CHECKED-IN FILE: Prometheus grew basic auth on
# 2026-08-08 when the SSO was parked (monitoring/prometheus-web.yml, gitignored).
# The portal is a browser app and cannot hold a credential, so the edge injects
# the Authorization header on its behalf. That header IS the credential, so the
# file it lives in must never be committed — hence this script writes it from
# ~/stacks/.env and .gitignore excludes the output.
#
# Re-run after changing DEV_LOGIN_USER / DEV_LOGIN_PASSWORD. Traefik's file
# provider watches ./dynamic, so no restart is needed — but see the bind-mount
# caveat in edge/compose.yml if you have just switched branches.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/edge/dynamic/portal-prom.yml"

[ -f "$root/.env" ] || { echo "no $root/.env — nothing to read credentials from" >&2; exit 1; }
set -a; . "$root/.env"; set +a
: "${DEV_LOGIN_USER:?set DEV_LOGIN_USER in .env}"
: "${DEV_LOGIN_PASSWORD:?set DEV_LOGIN_PASSWORD in .env}"

basic="$(printf '%s:%s' "$DEV_LOGIN_USER" "$DEV_LOGIN_PASSWORD" | base64 -w0)"

cat > "$out" <<YAML
# GENERATED by scripts/gen-portal-prom-route.sh — DO NOT COMMIT, DO NOT EDIT.
# Contains a basic-auth credential for Prometheus. Regenerate with:
#   just portal-prom-route
#
# The portal's time-series source. Same model as portal-api.yml: same-origin
# under /-/api/*, exact Path() only, read-only.
#
# ── SECURITY ───────────────────────────────────────────────────────────────
# Exactly TWO paths are routed, both of which only READ:
#   /-/api/prom/query        → instant vector
#   /-/api/prom/query_range  → range vector (the graphs)
# Never widen to PathPrefix. Prometheus also serves /api/v1/admin/tsdb/delete_series
# and, with --web.enable-lifecycle (which this instance runs), /-/reload and
# /-/quit. A PathPrefix here would hand all three to anything on the tailnet.
#
# What this does expose, unauthenticated, to the tailnet: every metric and every
# label value — container names, image names, mount paths, host interface names.
# The same categories /-/api/docker/containers/json already publishes. NOT Env,
# and no credential: the Authorization header is added here, on the way in, and
# is never visible to the browser.
http:
  routers:
    portal-api-prom:
      rule: >-
        Path(\`/-/api/prom/query\`)
        || Path(\`/-/api/prom/query_range\`)
      entryPoints: [web]
      priority: 100
      middlewares: [portal-api-prom-rewrite, portal-api-prom-auth]
      service: portal-prometheus

  middlewares:
    # /-/api/prom/query_range -> /api/v1/query_range
    portal-api-prom-rewrite:
      replacePathRegex:
        regex: "^/-/api/prom/(.*)"
        replacement: "/api/v1/\$1"

    # The credential the browser must not hold.
    portal-api-prom-auth:
      headers:
        customRequestHeaders:
          Authorization: "Basic $basic"

  services:
    portal-prometheus:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"
YAML

chmod 600 "$out"
echo "wrote $out (mode 600, gitignored)"
