#!/usr/bin/env python3
"""Generate bothy-ops' wiring from apps/bothy-ops/catalog.toml.   `just ops-wiring`

    python3 scripts/gen-ops-wiring.py            write the generated files
    python3 scripts/gen-ops-wiring.py --check    exit 1 (with a diff) if any is stale
    python3 scripts/gen-ops-wiring.py --out DIR  write them under DIR instead

The catalog is the only hand-written description of what the cluster tier may
do. Before 2026-09 the same ids were copied by hand into four places and a
check asserted the copies agreed; every new action was four edits and one
chance to get the Role wrong. Now the copies are OUTPUTS:

  edge/dynamic/bothy-ops.yml                  one exact Path() router per action
                                              (sso-viewer for a read, sso-operator
                                              for a change), the catalog route,
                                              and the three container verbs
  k8s/rbac/bothy-kube.yaml                    the Role in each of guard.NAMESPACES,
                                              merged from every action's `rbac`
  scripts/lib/bothy-kube-probes.sh            the can-i rows `just kube-token` prints:
                                              every granted verb must be yes, and
                                              the forbidden list must be no
  apps/bothy-web/web/src/lib/kube-catalog.dev.json
                                              what GET /-/api/kube/catalog serves,
                                              for `vite dev` and the web checks

guard.load_catalog validates the catalog first - including the rbac rules
(no secrets, exec, attach, portforward, watch, escalate, bind, impersonate;
create only on jobs; delete only on pods and jobs) - so a catalog that would
generate a dangerous Role never generates anything.

Stdlib plus tomllib. The YAML is written as text, not dumped: the edge file is
rendered by Traefik as a Go template, where a doubled curly brace anywhere
(comments included) voids the whole file, so every byte here is chosen.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import sys
import tempfile
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OPS = os.path.join(ROOT, "apps", "bothy-ops")
sys.path.insert(0, OPS)
sys.path.insert(0, os.path.join(ROOT, "apps", "bothy-common"))

import guard  # noqa: E402

EDGE = "edge/dynamic/bothy-ops.yml"
RBAC = "k8s/rbac/bothy-kube.yaml"
PROBES = "scripts/lib/bothy-kube-probes.sh"
DEVJSON = "apps/bothy-web/web/src/lib/kube-catalog.dev.json"
OUTPUTS = (EDGE, RBAC, PROBES, DEVJSON)

STAMP = "GENERATED by scripts/gen-ops-wiring.py from apps/bothy-ops/catalog.toml - DO NOT EDIT. Run `just ops-wiring`."

ROLE_MW = {"viewer": "sso-viewer", "operator": "sso-operator"}


def load() -> guard.Catalog:
    with open(os.path.join(OPS, "catalog.toml"), "rb") as fh:
        return guard.load_catalog(tomllib.load(fh))


# ── the edge ────────────────────────────────────────────────────────────────

EDGE_HEAD = """\
# {stamp}
#
# Routes for bothy-ops - everything that acts on something RUNNING: three verbs
# on a container, {n} actions on two cluster namespaces, and the catalog.
#
# WARNING - this directory is rendered as a Go template. A doubled curly brace
# anywhere, INCLUDING INSIDE A COMMENT, voids the whole file. Traefik then keeps
# serving its last-good config, so nothing looks wrong until the next restart,
# when every @file router disappears at once. `just verify` check 5b catches it,
# and the generator refuses to write one.
#
# ── one exact Path per verb and per action, never a prefix, never a Host ────
#
# These routers would collapse tidily into two PathPrefix rules and that is
# precisely the mistake. A prefix covers every endpoint the service grows LATER,
# including one nobody meant to expose; with exact paths a new verb or catalog
# action is unreachable until its router exists - the right default for the one
# service on this box that can stop a database. No Host() rules: the name layer
# is retired (notes rule 1).
#
# Separate routers rather than one rule with several Path() alternatives, because
# they are not one permission: the role of each is its catalog entry's `role`.
#
# ── gates are BORROWED, and from one place ──────────────────────────────────
#
#   sso-viewer, sso-operator   edge/dynamic/bothy-gates.yml
#   sso-errors                 edge/dynamic/auth.yml
#
# Never redefined here: two definitions of one name in one provider is a
# collision whose winner this file cannot decide. checks/wiring.py asserts that.
#
# sso-errors on these routes is consistency, not effect: every caller is a
# fetch() from lib/http.ts, so the sign-in page it substitutes for a 401 is bytes
# nobody renders - Traefik preserves the status, and the client reads that.

http:
  routers:
"""

EDGE_TAIL = """\
    # NO router for /healthz. It is the container's own HEALTHCHECK on 127.0.0.1;
    # publishing it would put the verb list, the deny list and the namespace scope
    # on the tailnet for nothing.

  middlewares:
    # /-/api/control/stop -> /control/stop, /-/api/kube/scale -> /kube/scale. The
    # service answers only its own paths, so it cannot accidentally be correct
    # about a path nobody routed. `/-/api`, not the longer prefix, because the
    # service's routes already carry /control/ and /kube/.
    bothy-ops-strip:
      stripPrefix:
        prefixes: ["/-/api"]

    # Delete any X-Auth-Request-* the CLIENT sent, before forwardAuth runs, so
    # the only identity that reaches the audit log is oauth2-proxy's. An empty
    # value in customRequestHeaders removes the header outright; relying on "the
    # auth response wins" would be relying on an ordering, not a guarantee.
    #
    # The blast radius if it were missing is a forged NAME in the action log, not
    # an unauthorised action - the gate reads a signed session cookie, never a
    # header. It matters more here than for a file write: a forged `stop
    # postgres` is over before anyone reads anything, and the log is the only
    # record it happened.
    ops-deidentify:
      headers:
        customRequestHeaders:
          X-Auth-Request-User: ""
          X-Auth-Request-Email: ""
          X-Auth-Request-Groups: ""
          X-Auth-Request-Preferred-Username: ""
          X-Forwarded-User: ""
          X-Forwarded-Email: ""

  services:
    bothy-ops:
      loadBalancer:
        servers:
          # opsnet holds exactly two containers: traefik and bothy-ops. The
          # service publishes no host port and authenticates nobody, so
          # reachability IS authorisation. Traefik is deliberately NOT on
          # controlsocknet (the proxies) or thales-scc (the apiserver).
          - url: "http://bothy-ops:8097"
"""


def _router(name: str, path: str, role: str, note: str = "") -> str:
    lead = f"    # {note}\n" if note else ""
    return (f"{lead}    {name}:\n"
            f"      rule: \"Path(`{path}`)\"\n"
            f"      entryPoints: [web]\n"
            f"      priority: 110\n"
            f"      service: bothy-ops\n"
            f"      middlewares: [bothy-ops-strip, ops-deidentify, {ROLE_MW[role]}, sso-errors]\n\n")


def gen_edge(cat: guard.Catalog) -> str:
    out = [EDGE_HEAD.format(stamp=STAMP, n=len(cat))]
    out.append("    # ══ containers: operator ═══════════════════════════════════════════════\n")
    for verb in guard.VERBS:
        out.append(_router(f"bothy-ops-control-{verb}", f"/-/api/control/{verb}", "operator"))
    out.append("    # NO read router for containers. What is running is already served by the\n"
               "    # portal's read-only Docker API (bothy-api.yml), and a second source of truth\n"
               "    # for container state would be two things to keep agreeing.\n\n")
    out.append("    # ══ cluster: the catalog itself (viewer) ═══════════════════════════════\n")
    out.append(_router("bothy-ops-kube-catalog", "/-/api/kube/catalog", "viewer",
                       "What the UI draws from. Static data from the image, no apiserver call."))
    for role, head in (("operator", "cluster changes: operator"), ("viewer", "cluster reads: viewer")):
        out.append(f"    # ══ {head} " + "═" * (69 - len(head)) + "\n")
        for a in cat.values():
            if a.role != role:
                continue
            note = ""
            if a.stream:
                note = ("text/event-stream when following; Traefik flushes that content type at once, "
                        "and the service bounds each stream to 300 s.")
            out.append(_router(f"bothy-ops-kube-{a.id}", f"/-/api/kube/{a.id}", role, note))
    out.append(EDGE_TAIL)
    text = "".join(out)
    if "{" + "{" in text or "}" + "}" in text:
        raise SystemExit("refusing to write an edge file with a doubled curly brace")
    return text


# ── the Role ────────────────────────────────────────────────────────────────

def merged_rules(cat: guard.Catalog) -> list[tuple[str, str, tuple[str, ...], list[str]]]:
    """[(group, resource, verbs, action ids)] - one rule per resource, sorted."""
    verbs: dict[tuple[str, str], set[str]] = {}
    users: dict[tuple[str, str], set[str]] = {}
    for a in cat.values():
        for g in a.rbac:
            k = (g.group, g.resource)
            verbs.setdefault(k, set()).update(g.verbs)
            users.setdefault(k, set()).add(a.id)
    order = {v: i for i, v in enumerate(guard.VERBS_K8S)}
    return [(grp, res, tuple(sorted(verbs[(grp, res)], key=order.__getitem__)), sorted(users[(grp, res)]))
            for grp, res in sorted(verbs, key=lambda k: (k[1].split("/")[0] != k[1], k[0], k[1]))]


RBAC_HEAD = """\
# {stamp}
#
# bothy-ops' identity in the cluster, and the whole of what it may do.
#
#   kubectl --context thales-scc apply -f k8s/rbac/bothy-kube.yaml    (just kube-token does it)
#
# Additive and namespaced: one Namespace (`bothy`) that holds the ServiceAccount
# and its token Secret and runs no pods, plus a Role and a RoleBinding in EACH of
# guard.NAMESPACES. There is no ClusterRole and no ClusterRoleBinding, so the
# account has no rights at all outside those namespaces - not even in its own.
# The ServiceAccount keeps the name `bothy-kube` from before the 2026-09 merge:
# renaming it would revoke the live token to re-issue the same grants.
#
# ── the grant, rule by rule, and the catalog actions that declared it ──────
#
{table}
#
# ── what is NOT here, on purpose (guard.py refuses to generate it) ─────────
#
#   pods/exec, pods/attach   a shell in a workload. Never from a browser.
#   pods/portforward         a tunnel into the cluster network.
#   secrets                  credentials, in any form. The Thales pods mount theirs
#                            as files (Kyverno thales-secret-handling); a Job made
#                            by run-template mounts `thales` the same way, and this
#                            account still cannot read it.
#   watch, update, deletecollection, escalate, bind, impersonate, `*`
#   anything cluster-scoped, including namespaces - create/delete of those is
#   impossible without a ClusterRole, and there is none
#
# The writes, and why each is bounded:
#   patch deployments        rollout-restart, pause/resume, set-image (image
#                            registry allowlist), rollback (same allowlist), and
#                            patch-key-and-restart's restart stamp
#   patch deployments/scale  scale 0..3 - the subresource cannot touch the pod spec
#   patch configmaps         resourceNames-limited to the catalog's `configmaps`;
#                            the service changes only allowlisted keys
#   delete pods              delete-pod (managed pods only, UID precondition) and
#                            delete-completed-pods (phase Succeeded only)
#   create/delete jobs       run-template (a file baked into the image) and
#                            delete-job. A Job's pod runs as the namespace's
#                            default ServiceAccount with no token mounted, under
#                            PSA restricted and the Kyverno SCC emulation.
#
# ── Kyverno and PSA ─────────────────────────────────────────────────────────
#
# Both target namespaces enforce PSA `restricted` and Kyverno's OpenShift-SCC
# emulation. Those policies match Pods (and the pods a Job creates); none of the
# objects below is subject to them. The `bothy` namespace is labelled restricted
# anyway: it should never run a pod.
apiVersion: v1
kind: Namespace
metadata:
  name: bothy
  labels:
    app.kubernetes.io/part-of: bothy
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bothy-kube
  namespace: bothy
  labels:
    app.kubernetes.io/part-of: bothy
# The token is not projected into any pod - nothing in the cluster runs as this
# account. It is used from OUTSIDE, by the bothy-ops container.
automountServiceAccountToken: false
"""


def _q(s: str) -> str:
    return json.dumps(s)


def gen_rbac(cat: guard.Catalog) -> str:
    rules = merged_rules(cat)
    width = max(len(r[1]) for r in rules) + 2
    table = []
    for grp, res, verbs, users in rules:
        names = " resourceNames " + ",".join(cat.policy.configmaps) if res == "configmaps" else ""
        table.append(f"#   {res.ljust(width)}{', '.join(verbs)}{names}")
        line = "#   " + " " * width + "<- "
        for i, u in enumerate(users):
            piece = u + (", " if i < len(users) - 1 else "")
            if len(line) + len(piece) > 80:
                table.append(line.rstrip())
                line = "#   " + " " * width + "   "
            line += piece
        table.append(line.rstrip())
    out = [RBAC_HEAD.format(stamp=STAMP, table="\n".join(table))]
    for ns in guard.NAMESPACES:
        out.append("---\napiVersion: rbac.authorization.k8s.io/v1\nkind: Role\nmetadata:\n"
                   f"  name: bothy-kube\n  namespace: {ns}\n  labels:\n    app.kubernetes.io/part-of: bothy\n"
                   "rules:\n")
        for grp, res, verbs, _ in rules:
            out.append(f"  - apiGroups: [{_q(grp)}]\n    resources: [{_q(res)}]\n")
            if res == "configmaps":
                out.append("    resourceNames: [" + ", ".join(_q(c) for c in cat.policy.configmaps) + "]\n")
            out.append("    verbs: [" + ", ".join(_q(v) for v in verbs) + "]\n")
        out.append("---\napiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding\nmetadata:\n"
                   f"  name: bothy-kube\n  namespace: {ns}\n  labels:\n    app.kubernetes.io/part-of: bothy\n"
                   "roleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: Role\n  name: bothy-kube\n"
                   "subjects:\n  - kind: ServiceAccount\n    name: bothy-kube\n    namespace: bothy\n")
    return "".join(out)


# ── the can-i rows ──────────────────────────────────────────────────────────

# Every one of these must answer `no`. They are the refusals the design rests
# on, asked of the apiserver rather than of a file.
MUST_NOT = [
    ("create", "pods --exec", "{ns}"),
    ("get", "pods --exec", "{ns}"),
    ("create", "pods --attach", "{ns}"),
    ("get", "pods --attach", "{ns}"),
    ("create", "pods --portforward", "{ns}"),
    ("get", "pods --portforward", "{ns}"),
    ("get", "secrets", "{ns}"),
    ("list", "secrets", "{ns}"),
    ("get", "secrets/thales", "{ns}"),
    ("watch", "pods", "{ns}"),
    ("watch", "events", "{ns}"),
    ("create", "pods", "{ns}"),
    ("create", "deployments.apps", "{ns}"),
    ("update", "deployments.apps", "{ns}"),
    ("deletecollection", "pods", "{ns}"),
    ("get", "configmaps/kube-root-ca.crt", "{ns}"),
    ("list", "configmaps", "{ns}"),
    ("escalate", "roles.rbac.authorization.k8s.io", "{ns}"),
    ("bind", "roles.rbac.authorization.k8s.io", "{ns}"),
    ("create", "rolebindings.rbac.authorization.k8s.io", "{ns}"),
    ("impersonate", "serviceaccounts", "{ns}"),
    ("create", "serviceaccounts --token", "{ns}"),
]
MUST_NOT_ANYWHERE = [
    ("create", "namespaces", "-"),
    ("delete", "namespaces", "-"),
    ("get", "secrets", "bothy"),
    ("list", "pods", "kube-system"),
    ("patch", "deployments.apps", "thales"),
    ("create", "jobs.batch", "kube-system"),
    ("list", "nodes", "-"),
]


def _can_i_resource(grp: str, res: str) -> str:
    """`deployments.apps --scale`: the probe passes the part after `--` as
    --subresource. NOT `deployments.apps/scale` - `kubectl auth can-i` reads
    TYPE/NAME there, so that spelling asks about a deployment NAMED scale, and
    `get pods/exec` quietly answers `get pods` (found 2026-09-17: it said yes)."""
    base, _, sub = res.partition("/")
    full = f"{base}.{grp}" if grp else base
    return f"{full} --{sub}" if sub else full


def _row(expect: str, verb: str, res: str, ns: str) -> str:
    base, _, sub = res.partition(" --")
    return f"probe {expect} {verb} {base} {ns}" + (f" --{sub}" if sub else "")


def gen_probes(cat: guard.Catalog) -> str:
    rows = [f"# {STAMP}",
            "#",
            "# Sourced by scripts/gen-kube-token.sh, which defines",
            "#   probe <expect yes|no> <verb> <resource[/name]> <namespace or - for cluster scope> [--<subresource>]",
            "# `configmaps/thales` is a NAME (resourceNames). A subresource is never written",
            "# `pods/exec`: can-i reads that as a pod named exec, and answers for `get pods`.",
            "# Every verb the generated Role grants must be yes; the refusals must be no.",
            ""]
    for ns in guard.NAMESPACES:
        rows.append(f"# ── {ns}: granted ──")
        for grp, res, verbs, _ in merged_rules(cat):
            targets = ([f"{_can_i_resource(grp, res)}/{c}" for c in cat.policy.configmaps]
                       if res == "configmaps" else [_can_i_resource(grp, res)])
            for t in targets:
                for v in verbs:
                    rows.append(_row("yes", v, t, ns))
        rows.append(f"# ── {ns}: refused ──")
        for v, r, n in MUST_NOT:
            rows.append(_row("no", v, r, n.format(ns=ns)))
    rows.append("# ── outside the two namespaces, and cluster scope ──")
    for v, r, n in MUST_NOT_ANYWHERE:
        rows.append(_row("no", v, r, n))
    return "\n".join(rows) + "\n"


def gen_devjson(cat: guard.Catalog) -> str:
    return json.dumps(guard.catalog_json(cat), indent=2) + "\n"


# ── driver ──────────────────────────────────────────────────────────────────

def render() -> dict[str, str]:
    cat = load()
    return {EDGE: gen_edge(cat), RBAC: gen_rbac(cat), PROBES: gen_probes(cat), DEVJSON: gen_devjson(cat)}


def write(files: dict[str, str], root: str) -> None:
    for rel, text in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)


def check(files: dict[str, str]) -> int:
    """Write into a temp dir and diff against the tree - the same bytes `write` would produce."""
    stale = 0
    with tempfile.TemporaryDirectory(prefix="ops-wiring-") as tmp:
        write(files, tmp)
        for rel in OUTPUTS:
            want = open(os.path.join(tmp, rel), encoding="utf-8").read()
            try:
                have = open(os.path.join(ROOT, rel), encoding="utf-8").read()
            except OSError:
                have = ""
            if want != have:
                stale += 1
                print(f"STALE  {rel}")
                sys.stdout.writelines(list(difflib.unified_diff(
                    have.splitlines(True), want.splitlines(True), f"a/{rel}", f"b/{rel}"))[:80])
            else:
                print(f"ok     {rel}")
    if stale:
        print(f"\n{stale} generated file(s) out of date - run `just ops-wiring` and commit the result.")
    return 1 if stale else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--check", action="store_true", help="fail if a generated file is stale")
    ap.add_argument("--out", help="write under this directory instead of the repository")
    args = ap.parse_args()
    try:
        files = render()
    except guard.CatalogError as e:
        print(f"catalog.toml is invalid: {e}", file=sys.stderr)
        return 2
    if args.check:
        return check(files)
    write(files, args.out or ROOT)
    for rel in OUTPUTS:
        print(f"wrote  {os.path.join(args.out, rel) if args.out else rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
