#!/usr/bin/env python3
"""Generate the cluster wiring from its two declarations.   `just ops-wiring`

    python3 scripts/gen-ops-wiring.py            write the generated files
    python3 scripts/gen-ops-wiring.py --check    exit 1 (with a diff) if any is stale
    python3 scripts/gen-ops-wiring.py --out DIR  write them under DIR instead

Two accounts reach the cluster from this box and each has ONE hand-written
declaration of what it may do; everything else is rendered from it. The second
account joined this script on 2026-09-23 rather than getting a generator of its
own: a Role and its can-i proof are the same problem twice, and one `--check` in
CI (ci.yml) covering both is what stops either drifting from review.

    apps/bothy-ops/catalog.toml       bothy-ops - what a browser may do to the cluster
    apps/bothy-collector/reads.toml   bothy-collector - what the portal's 30 s timer reads

The catalog is the only hand-written description of what the cluster tier may
do. Before 2026-09 the same ids were copied by hand into four places and a
check asserted the copies agreed; every new action was four edits and one
chance to get the Role wrong. Now the copies are OUTPUTS:

  edge/dynamic/bothy-ops.yml                  one exact Path() router per action
                                              (sso-viewer for a read, sso-operator
                                              for a change), the catalog route,
                                              and the three container verbs
  k8s/rbac/bothy-kube.yaml                    the Role in each of guard.NAMESPACES,
                                              merged from every action's `rbac`
  scripts/lib/bothy-kube-probes.sh            the can-i rows `just kube-token` prints:
                                              every granted verb must be yes, and
                                              the forbidden list must be no
  apps/bothy-web/web/src/lib/kube-catalog.dev.json
                                              what GET /-/api/kube/catalog serves,
                                              for `vite dev` and the web checks

and, from reads.toml:

  k8s/rbac/bothy-collector.yaml               the ServiceAccount, the list-only
                                              ClusterRole and its binding
  scripts/lib/bothy-collector-probes.sh       the can-i rows `just collector-token`
                                              prints - every granted list, then
                                              the refusals

guard.load_catalog validates the catalog first - including the rbac rules
(no secrets, exec, attach, portforward, watch, escalate, bind, impersonate;
create only on jobs; delete only on pods and jobs) - so a catalog that would
generate a dangerous Role never generates anything. load_reads() does the same
for reads.toml, where the rule is stricter still: every row is a `list`, the
verb is not even spellable in the file, and `secrets` is refused by name.

Stdlib plus tomllib. The YAML is written as text, not dumped: the edge file is
rendered by Traefik as a Go template, where a doubled curly brace anywhere
(comments included) voids the whole file, so every byte here is chosen.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import sys
import tempfile
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OPS = os.path.join(ROOT, "apps", "bothy-ops")
sys.path.insert(0, OPS)
sys.path.insert(0, os.path.join(ROOT, "apps", "bothy-common"))

import guard  # noqa: E402

EDGE = "edge/dynamic/bothy-ops.yml"
RBAC = "k8s/rbac/bothy-kube.yaml"
PROBES = "scripts/lib/bothy-kube-probes.sh"
DEVJSON = "apps/bothy-web/web/src/lib/kube-catalog.dev.json"
COLL_RBAC = "k8s/rbac/bothy-collector.yaml"
COLL_PROBES = "scripts/lib/bothy-collector-probes.sh"
OUTPUTS = (EDGE, RBAC, PROBES, DEVJSON, COLL_RBAC, COLL_PROBES)

READS = "apps/bothy-collector/reads.toml"

STAMP = "GENERATED by scripts/gen-ops-wiring.py from apps/bothy-ops/catalog.toml - DO NOT EDIT. Run `just ops-wiring`."
COLL_STAMP = f"GENERATED by scripts/gen-ops-wiring.py from {READS} - DO NOT EDIT. Run `just ops-wiring`."

ROLE_MW = {"viewer": "sso-viewer", "operator": "sso-operator"}


class ReadsError(Exception):
    """reads.toml describes something that must not become a ClusterRole."""


def load() -> guard.Catalog:
    with open(os.path.join(OPS, "catalog.toml"), "rb") as fh:
        return guard.load_catalog(tomllib.load(fh))


# ── the edge ────────────────────────────────────────────────────────────────

EDGE_HEAD = """\
# {stamp}
#
# Routes for bothy-ops - everything that acts on something RUNNING: three verbs
# on a container, {n} actions on two cluster namespaces, and the catalog.
#
# WARNING - this directory is rendered as a Go template. A doubled curly brace
# anywhere, INCLUDING INSIDE A COMMENT, voids the whole file. Traefik then keeps
# serving its last-good config, so nothing looks wrong until the next restart,
# when every @file router disappears at once. `just verify` check 5b catches it,
# and the generator refuses to write one.
#
# ── one exact Path per verb and per action, never a prefix, never a Host ────
#
# These routers would collapse tidily into two PathPrefix rules and that is
# precisely the mistake. A prefix covers every endpoint the service grows LATER,
# including one nobody meant to expose; with exact paths a new verb or catalog
# action is unreachable until its router exists - the right default for the one
# service on this box that can stop a database. No Host() rules: the name layer
# is retired (notes rule 1).
#
# Separate routers rather than one rule with several Path() alternatives, because
# they are not one permission: the role of each is its catalog entry's `role`.
#
# ── gates are BORROWED, and from one place ──────────────────────────────────
#
#   sso-viewer, sso-operator   edge/dynamic/bothy-gates.yml
#   sso-errors                 edge/dynamic/auth.yml
#
# Never redefined here: two definitions of one name in one provider is a
# collision whose winner this file cannot decide. checks/wiring.py asserts that.
#
# sso-errors on these routes is consistency, not effect: every caller is a
# fetch() from lib/http.ts, so the sign-in page it substitutes for a 401 is bytes
# nobody renders - Traefik preserves the status, and the client reads that.

http:
  routers:
"""

EDGE_TAIL = """\
    # NO router for /healthz. It is the container's own HEALTHCHECK on 127.0.0.1;
    # publishing it would put the verb list, the deny list and the namespace scope
    # on the tailnet for nothing.

  middlewares:
    # /-/api/control/stop -> /control/stop, /-/api/kube/scale -> /kube/scale. The
    # service answers only its own paths, so it cannot accidentally be correct
    # about a path nobody routed. `/-/api`, not the longer prefix, because the
    # service's routes already carry /control/ and /kube/.
    bothy-ops-strip:
      stripPrefix:
        prefixes: ["/-/api"]

    # Delete any X-Auth-Request-* the CLIENT sent, before forwardAuth runs, so
    # the only identity that reaches the audit log is oauth2-proxy's. An empty
    # value in customRequestHeaders removes the header outright; relying on "the
    # auth response wins" would be relying on an ordering, not a guarantee.
    #
    # The blast radius if it were missing is a forged NAME in the action log, not
    # an unauthorised action - the gate reads a signed session cookie, never a
    # header. It matters more here than for a file write: a forged `stop
    # postgres` is over before anyone reads anything, and the log is the only
    # record it happened.
    ops-deidentify:
      headers:
        customRequestHeaders:
          X-Auth-Request-User: ""
          X-Auth-Request-Email: ""
          X-Auth-Request-Groups: ""
          X-Auth-Request-Preferred-Username: ""
          X-Forwarded-User: ""
          X-Forwarded-Email: ""

  services:
    bothy-ops:
      loadBalancer:
        servers:
          # opsnet holds exactly two containers: traefik and bothy-ops. The
          # service publishes no host port and authenticates nobody, so
          # reachability IS authorisation. Traefik is deliberately NOT on
          # controlsocknet (the proxies) or thales-scc (the apiserver).
          - url: "http://bothy-ops:8097"
"""


def _router(name: str, path: str, role: str, note: str = "") -> str:
    lead = f"    # {note}\n" if note else ""
    return (f"{lead}    {name}:\n"
            f"      rule: \"Path(`{path}`)\"\n"
            f"      entryPoints: [web]\n"
            f"      priority: 110\n"
            f"      service: bothy-ops\n"
            f"      middlewares: [bothy-ops-strip, ops-deidentify, {ROLE_MW[role]}, sso-errors]\n\n")


def gen_edge(cat: guard.Catalog) -> str:
    out = [EDGE_HEAD.format(stamp=STAMP, n=len(cat))]
    out.append("    # ══ containers: operator ═══════════════════════════════════════════════\n")
    for verb in guard.VERBS:
        out.append(_router(f"bothy-ops-control-{verb}", f"/-/api/control/{verb}", "operator"))
    out.append("    # NO read router for containers. What is running is already served by the\n"
               "    # portal's read-only Docker API (bothy-api.yml), and a second source of truth\n"
               "    # for container state would be two things to keep agreeing.\n\n")
    out.append("    # ══ cluster: the catalog itself (viewer) ═══════════════════════════════\n")
    out.append(_router("bothy-ops-kube-catalog", "/-/api/kube/catalog", "viewer",
                       "What the UI draws from. Static data from the image, no apiserver call."))
    for role, head in (("operator", "cluster changes: operator"), ("viewer", "cluster reads: viewer")):
        out.append(f"    # ══ {head} " + "═" * (69 - len(head)) + "\n")
        for a in cat.values():
            if a.role != role:
                continue
            note = ""
            if a.stream:
                note = ("text/event-stream when following; Traefik flushes that content type at once, "
                        "and the service bounds each stream to 300 s.")
            out.append(_router(f"bothy-ops-kube-{a.id}", f"/-/api/kube/{a.id}", role, note))
    out.append(EDGE_TAIL)
    text = "".join(out)
    if "{" + "{" in text or "}" + "}" in text:
        raise SystemExit("refusing to write an edge file with a doubled curly brace")
    return text


# ── the Role ────────────────────────────────────────────────────────────────

def merged_rules(cat: guard.Catalog) -> list[tuple[str, str, tuple[str, ...], list[str]]]:
    """[(group, resource, verbs, action ids)] - one rule per resource, sorted."""
    verbs: dict[tuple[str, str], set[str]] = {}
    users: dict[tuple[str, str], set[str]] = {}
    for a in cat.values():
        for g in a.rbac:
            k = (g.group, g.resource)
            verbs.setdefault(k, set()).update(g.verbs)
            users.setdefault(k, set()).add(a.id)
    order = {v: i for i, v in enumerate(guard.VERBS_K8S)}
    return [(grp, res, tuple(sorted(verbs[(grp, res)], key=order.__getitem__)), sorted(users[(grp, res)]))
            for grp, res in sorted(verbs, key=lambda k: (k[1].split("/")[0] != k[1], k[0], k[1]))]


RBAC_HEAD = """\
# {stamp}
#
# bothy-ops' identity in the cluster, and the whole of what it may do.
#
#   kubectl --context thales-scc apply -f k8s/rbac/bothy-kube.yaml    (just kube-token does it)
#
# Additive and namespaced: one Namespace (`bothy`) that holds the ServiceAccount
# and its token Secret and runs no pods, plus a Role and a RoleBinding in EACH of
# guard.NAMESPACES. There is no ClusterRole and no ClusterRoleBinding, so the
# account has no rights at all outside those namespaces - not even in its own.
# The ServiceAccount keeps the name `bothy-kube` from before the 2026-09 merge:
# renaming it would revoke the live token to re-issue the same grants.
#
# ── the grant, rule by rule, and the catalog actions that declared it ──────
#
{table}
#
# ── what is NOT here, on purpose (guard.py refuses to generate it) ─────────
#
#   pods/exec, pods/attach   a shell in a workload. Never from a browser.
#   pods/portforward         a tunnel into the cluster network.
#   secrets                  credentials, in any form. The Thales pods mount theirs
#                            as files (Kyverno thales-secret-handling); a Job made
#                            by run-template mounts `thales` the same way, and this
#                            account still cannot read it.
#   watch, update, deletecollection, escalate, bind, impersonate, `*`
#   anything cluster-scoped, including namespaces - create/delete of those is
#   impossible without a ClusterRole, and there is none
#
# The writes, and why each is bounded:
#   patch deployments        rollout-restart, pause/resume, set-image (image
#                            registry allowlist), rollback (same allowlist), and
#                            patch-key-and-restart's restart stamp
#   patch deployments/scale  scale 0..3 - the subresource cannot touch the pod spec
#   patch configmaps         resourceNames-limited to the catalog's `configmaps`;
#                            the service changes only allowlisted keys
#   delete pods              delete-pod (managed pods only, UID precondition) and
#                            delete-completed-pods (phase Succeeded only)
#   create/delete jobs       run-template (a file baked into the image) and
#                            delete-job. A Job's pod runs as the namespace's
#                            default ServiceAccount with no token mounted, under
#                            PSA restricted and the Kyverno SCC emulation.
#
# ── Kyverno and PSA ─────────────────────────────────────────────────────────
#
# Both target namespaces enforce PSA `restricted` and Kyverno's OpenShift-SCC
# emulation. Those policies match Pods (and the pods a Job creates); none of the
# objects below is subject to them. The `bothy` namespace is labelled restricted
# anyway: it should never run a pod.
apiVersion: v1
kind: Namespace
metadata:
  name: bothy
  labels:
    app.kubernetes.io/part-of: bothy
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bothy-kube
  namespace: bothy
  labels:
    app.kubernetes.io/part-of: bothy
# The token is not projected into any pod - nothing in the cluster runs as this
# account. It is used from OUTSIDE, by the bothy-ops container.
automountServiceAccountToken: false
"""


def _q(s: str) -> str:
    return json.dumps(s)


def gen_rbac(cat: guard.Catalog) -> str:
    rules = merged_rules(cat)
    width = max(len(r[1]) for r in rules) + 2
    table = []
    for grp, res, verbs, users in rules:
        names = " resourceNames " + ",".join(cat.policy.configmaps) if res == "configmaps" else ""
        table.append(f"#   {res.ljust(width)}{', '.join(verbs)}{names}")
        line = "#   " + " " * width + "<- "
        for i, u in enumerate(users):
            piece = u + (", " if i < len(users) - 1 else "")
            if len(line) + len(piece) > 80:
                table.append(line.rstrip())
                line = "#   " + " " * width + "   "
            line += piece
        table.append(line.rstrip())
    out = [RBAC_HEAD.format(stamp=STAMP, table="\n".join(table))]
    for ns in guard.NAMESPACES:
        out.append("---\napiVersion: rbac.authorization.k8s.io/v1\nkind: Role\nmetadata:\n"
                   f"  name: bothy-kube\n  namespace: {ns}\n  labels:\n    app.kubernetes.io/part-of: bothy\n"
                   "rules:\n")
        for grp, res, verbs, _ in rules:
            out.append(f"  - apiGroups: [{_q(grp)}]\n    resources: [{_q(res)}]\n")
            if res == "configmaps":
                out.append("    resourceNames: [" + ", ".join(_q(c) for c in cat.policy.configmaps) + "]\n")
            out.append("    verbs: [" + ", ".join(_q(v) for v in verbs) + "]\n")
        out.append("---\napiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding\nmetadata:\n"
                   f"  name: bothy-kube\n  namespace: {ns}\n  labels:\n    app.kubernetes.io/part-of: bothy\n"
                   "roleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: Role\n  name: bothy-kube\n"
                   "subjects:\n  - kind: ServiceAccount\n    name: bothy-kube\n    namespace: bothy\n")
    return "".join(out)


# ── the can-i rows ──────────────────────────────────────────────────────────

# Every one of these must answer `no`. They are the refusals the design rests
# on, asked of the apiserver rather than of a file.
MUST_NOT = [
    ("create", "pods --exec", "{ns}"),
    ("get", "pods --exec", "{ns}"),
    ("create", "pods --attach", "{ns}"),
    ("get", "pods --attach", "{ns}"),
    ("create", "pods --portforward", "{ns}"),
    ("get", "pods --portforward", "{ns}"),
    ("get", "secrets", "{ns}"),
    ("list", "secrets", "{ns}"),
    ("get", "secrets/thales", "{ns}"),
    ("watch", "pods", "{ns}"),
    ("watch", "events", "{ns}"),
    ("create", "pods", "{ns}"),
    ("create", "deployments.apps", "{ns}"),
    ("update", "deployments.apps", "{ns}"),
    ("deletecollection", "pods", "{ns}"),
    ("get", "configmaps/kube-root-ca.crt", "{ns}"),
    ("list", "configmaps", "{ns}"),
    ("escalate", "roles.rbac.authorization.k8s.io", "{ns}"),
    ("bind", "roles.rbac.authorization.k8s.io", "{ns}"),
    ("create", "rolebindings.rbac.authorization.k8s.io", "{ns}"),
    ("impersonate", "serviceaccounts", "{ns}"),
    ("create", "serviceaccounts --token", "{ns}"),
]
MUST_NOT_ANYWHERE = [
    ("create", "namespaces", "-"),
    ("delete", "namespaces", "-"),
    ("get", "secrets", "bothy"),
    ("list", "pods", "kube-system"),
    ("patch", "deployments.apps", "thales"),
    ("create", "jobs.batch", "kube-system"),
    ("list", "nodes", "-"),
]


def _can_i_resource(grp: str, res: str) -> str:
    """`deployments.apps --scale`: the probe passes the part after `--` as
    --subresource. NOT `deployments.apps/scale` - `kubectl auth can-i` reads
    TYPE/NAME there, so that spelling asks about a deployment NAMED scale, and
    `get pods/exec` quietly answers `get pods` (found 2026-09-17: it said yes)."""
    base, _, sub = res.partition("/")
    full = f"{base}.{grp}" if grp else base
    return f"{full} --{sub}" if sub else full


def _row(expect: str, verb: str, res: str, ns: str) -> str:
    base, _, sub = res.partition(" --")
    return f"probe {expect} {verb} {base} {ns}" + (f" --{sub}" if sub else "")


def gen_probes(cat: guard.Catalog) -> str:
    rows = ["# shellcheck shell=bash",
            f"# {STAMP}",
            "#",
            "# Sourced by scripts/gen-kube-token.sh, which defines",
            "#   probe <expect yes|no> <verb> <resource[/name]> <namespace or - for cluster scope> [--<subresource>]",
            "# `configmaps/thales` is a NAME (resourceNames). A subresource is never written",
            "# `pods/exec`: can-i reads that as a pod named exec, and answers for `get pods`.",
            "# Every verb the generated Role grants must be yes; the refusals must be no.",
            ""]
    for ns in guard.NAMESPACES:
        rows.append(f"# ── {ns}: granted ──")
        for grp, res, verbs, _ in merged_rules(cat):
            targets = ([f"{_can_i_resource(grp, res)}/{c}" for c in cat.policy.configmaps]
                       if res == "configmaps" else [_can_i_resource(grp, res)])
            for t in targets:
                for v in verbs:
                    rows.append(_row("yes", v, t, ns))
        rows.append(f"# ── {ns}: refused ──")
        for v, r, n in MUST_NOT:
            rows.append(_row("no", v, r, n.format(ns=ns)))
    rows.append("# ── outside the two namespaces, and cluster scope ──")
    for v, r, n in MUST_NOT_ANYWHERE:
        rows.append(_row("no", v, r, n))
    return "\n".join(rows) + "\n"


def gen_devjson(cat: guard.Catalog) -> str:
    return json.dumps(guard.catalog_json(cat), indent=2) + "\n"


# ── bothy-collector: the portal's 30-second cluster read ────────────────────
#
# Same shape as everything above - a declaration in, a Role and its can-i proof
# out - for the other account that touches the cluster from this box.

READ_KEYS = {"id", "resource", "group", "scope", "why"}
READ_SCOPES = ("cluster", "all-namespaces")
# Refused by name rather than left to review. `secrets` is the read that is a
# credential; the rest are the resources whose bodies carry more than a picture
# of what is deployed, and none of them appears in collect.py.
READS_DENY = {"secrets", "serviceaccounts", "roles", "rolebindings",
              "clusterroles", "clusterrolebindings", "nodes", "*"}


def load_reads(path: str | None = None) -> list[dict[str, str]]:
    """reads.toml -> the rows, validated. Raises rather than generating a Role
    nobody would sign off: no verb is spellable (every row is a `list`), no
    subresource, no wildcard, and the deny list above by name."""
    with open(path or os.path.join(ROOT, READS), "rb") as fh:
        raw = tomllib.load(fh)
    rows: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for i, r in enumerate(raw.get("read") or []):
        extra = set(r) - READ_KEYS
        if extra:
            # A `verbs = ["delete"]` here would otherwise sit in the file looking
            # effective while the generator ignored it - the worst kind of
            # security config, one that reads as a grant and is not one.
            raise ReadsError(f"read {i}: unknown key(s) {sorted(extra)}; only {sorted(READ_KEYS)} exist")
        missing = READ_KEYS - set(r)
        if missing:
            raise ReadsError(f"read {i}: missing {sorted(missing)}")
        if not all(isinstance(r[k], str) for k in READ_KEYS):
            raise ReadsError(f"read {i}: every value must be a string")
        if r["scope"] not in READ_SCOPES:
            raise ReadsError(f"read {r['id']}: scope must be one of {READ_SCOPES}")
        if "/" in r["resource"] or "*" in r["resource"] + r["group"]:
            raise ReadsError(f"read {r['id']}: no subresources and no wildcards")
        if r["resource"] in READS_DENY:
            raise ReadsError(f"read {r['id']}: `{r['resource']}` is refused here, whatever it is for")
        key = (r["group"], r["resource"])
        if key in seen:
            raise ReadsError(f"read {r['id']}: {key} is declared twice")
        seen.add(key)
        rows.append({k: r[k] for k in READ_KEYS})
    if not rows:
        raise ReadsError("no [[read]] rows - that would generate an empty ClusterRole")
    return sorted(rows, key=lambda r: (r["group"], r["resource"]))


def _can_i_target(row: dict[str, str]) -> str:
    return f"{row['resource']}.{row['group']}" if row["group"] else row["resource"]


COLL_RBAC_HEAD = """\
# {stamp}
#
# bothy-collector's identity in the cluster, and the whole of what it may do.
#
#   kubectl --context thales-scc apply -f k8s/rbac/bothy-collector.yaml
#   (just collector-token does it)
#
# The account the portal's discovery timer reads the cluster with, every 30
# seconds, from the host. Until 2026-09-23 there was no account: collect.py ran
# as devssh with ~/.kube/config, which on minikube is the admin client
# certificate - user `minikube-user` in group `system:masters`, which does not
# hold cluster-admin so much as SKIP RBAC. Every Secret in the cluster, every
# exec, every delete, `minikube`'s whole cluster, held permanently by a timer
# that lists five kinds of object and writes a JSON file. The rules below are
# the entirety of what that timer ever used.
#
# ── the grant, rule by rule, and the read that declared it ─────────────────
#
{table}
#
# ── why a ClusterRole, when bothy-kube deliberately has none ───────────────
#
# Because the collector's subject is the SET of namespaces, which is discovered
# and not declared. `kubectl get deployments --all-namespaces` is one
# cluster-scoped LIST, not a loop of namespaced ones, so a Role cannot authorise
# it however many namespaces it exists in; and the namespaces it would have to
# exist in are exactly the ones nobody has created yet. bothy-kube is the
# opposite case - two named namespaces, fixed in guard.NAMESPACES - so it gets
# Roles and this gets a ClusterRole, and each is the narrowest thing that works.
#
# The cost, stated rather than hidden: this account can enumerate the four
# namespaced kinds below in kube-system too. collect.py drops those client-side
# (K8S_SKIP_NS); RBAC has no way to express "every namespace except", and
# inventing one out of a hand-written namespace list would replace a discovered
# portal with a maintained one.
#
# ── what is NOT here, on purpose (load_reads refuses to generate it) ───────
#
#   get                      not granted, so not even one named object. `kubectl
#                            get <plural>` with no name is a LIST; nothing here
#                            ever fetches by name, so `get` would be a verb
#                            granted for a call that does not exist.
#   watch                    a 30-second timer does not need a stream, and an
#                            open watch is a connection the apiserver holds for
#                            an account that should be asleep between runs.
#   secrets, configmaps      credentials and config. Neither is read by collect.py.
#   pods, pods/log           the collector reports DEPLOYMENTS; pod bodies and
#                            their logs are Headlamp's job (bothy-browse) and
#                            bothy-ops', each with its own account.
#   pods/exec, attach, portforward, and every write verb - create, update,
#   patch, delete, deletecollection, escalate, bind, impersonate, `*`
#
# ── one ServiceAccount per consumer, and why not just reuse `view` ─────────
#
# bothy-browse (Headlamp) is already bound to the built-in `view` ClusterRole
# cluster-wide, and reusing it here would have been one line. `view` grants
# get/list/watch on some sixty kinds - pods, pod logs, configmaps, PVCs,
# serviceaccounts, events - where this needs list on five, and a shared account
# means revoking one consumer revokes the other. Separate accounts also make the
# audit log say WHICH thing read the cluster.
apiVersion: v1
kind: Namespace
metadata:
  name: bothy
  labels:
    app.kubernetes.io/part-of: bothy
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bothy-collector
  namespace: bothy
  labels:
    app.kubernetes.io/part-of: bothy
    app.kubernetes.io/name: bothy-collector
# The token is a Secret created by scripts/gen-collector-token.sh, never mounted
# into a pod - nothing runs as this account inside the cluster. It is used from
# OUTSIDE, by the host timer bothy-collector.service.
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bothy-collector
  labels:
    app.kubernetes.io/part-of: bothy
    app.kubernetes.io/name: bothy-collector
rules:
"""

COLL_RBAC_TAIL = """\
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bothy-collector
  labels:
    app.kubernetes.io/part-of: bothy
    app.kubernetes.io/name: bothy-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bothy-collector
subjects:
  - kind: ServiceAccount
    name: bothy-collector
    namespace: bothy
"""


def gen_collector_rbac(rows: list[dict[str, str]]) -> str:
    width = max(len(r["resource"]) for r in rows) + 2
    table = []
    for r in rows:
        table.append(f"#   {r['resource'].ljust(width)}list")
        table.append(f"#   {' ' * width}<- {r['id']}: {r['why']}")
    out = [COLL_RBAC_HEAD.format(stamp=COLL_STAMP, table="\n".join(table))]
    for r in rows:
        out.append(f"  - apiGroups: [{_q(r['group'])}]\n"
                   f"    resources: [{_q(r['resource'])}]\n"
                   f"    verbs: [\"list\"]\n")
    out.append(COLL_RBAC_TAIL)
    return "".join(out)


# Every one of these must answer `no`. They are asked of the apiserver, not of
# this file. Scope is a namespace, `-A` for every namespace, or `-` for cluster
# scope. `thales-pre-prod` is a namespace the collector genuinely reports on and
# `kube-system` one it throws away, so both are worth asking about.
COLL_MUST_NOT = [
    # the reads that are credentials, in every scope that exists
    ("list", "secrets", "-A"),
    ("get", "secrets", "thales-pre-prod"),
    ("get", "secrets", "bothy"),
    ("list", "configmaps", "-A"),
    # list is granted, get is not - one named object is a different request
    ("get", "deployments.apps", "thales-pre-prod"),
    ("get", "namespaces", "-"),
    ("watch", "deployments.apps", "-A"),
    # the kinds the collector does not read at all
    ("list", "pods", "-A"),
    ("get", "pods/log", "thales-pre-prod"),
    ("list", "nodes", "-"),
    ("list", "persistentvolumeclaims", "-A"),
    ("list", "events", "-A"),
    ("list", "serviceaccounts", "-A"),
    ("list", "roles.rbac.authorization.k8s.io", "-A"),
    ("list", "clusterroles.rbac.authorization.k8s.io", "-"),
    # a shell, a tunnel, a token
    ("create", "pods/exec", "thales-pre-prod"),
    ("get", "pods/exec", "thales-pre-prod"),
    ("create", "pods/attach", "thales-pre-prod"),
    ("create", "pods/portforward", "thales-pre-prod"),
    ("create", "serviceaccounts/token", "bothy"),
    ("impersonate", "serviceaccounts", "bothy"),
    ("escalate", "clusterroles.rbac.authorization.k8s.io", "-"),
    ("bind", "clusterroles.rbac.authorization.k8s.io", "-"),
    # every write, in a namespace it reports on and in kube-system
    ("create", "deployments.apps", "thales-pre-prod"),
    ("update", "deployments.apps", "thales-pre-prod"),
    ("patch", "deployments.apps", "thales-pre-prod"),
    ("delete", "deployments.apps", "thales-pre-prod"),
    ("patch", "deployments.apps", "kube-system"),
    ("delete", "pods", "kube-system"),
    ("create", "jobs.batch", "kube-system"),
    ("deletecollection", "pods", "-A"),
    ("create", "namespaces", "-"),
    ("delete", "namespaces", "-"),
]


def gen_collector_probes(rows: list[dict[str, str]]) -> str:
    out = ["# shellcheck shell=bash",
           f"# {COLL_STAMP}",
           "#",
           "# Sourced by scripts/gen-collector-token.sh, which defines",
           "#   probe <expect yes|no> <verb> <resource[/subresource]> <namespace | -A | - >",
           "# A subresource is written `pods/exec` here and goes to can-i as",
           "# --subresource=exec: `can-i get pods/exec` reads TYPE/NAME, so it asks about a",
           "# pod NAMED exec and answers for `get pods` (found 2026-09-17 in the other two",
           "# scripts, where it printed yes for a grant that did not exist).",
           "#",
           "# Every read reads.toml declares must be yes; every refusal must be no.",
           "",
           "# ── granted: list, and only list ──"]
    for r in rows:
        scope = "-" if r["scope"] == "cluster" else "-A"
        out.append(f"probe yes list {_can_i_target(r)} {scope}")
    out.append("# ── refused ──")
    for verb, res, scope in COLL_MUST_NOT:
        out.append(f"probe no {verb} {res} {scope}")
    return "\n".join(out) + "\n"


# ── driver ──────────────────────────────────────────────────────────────────

def render() -> dict[str, str]:
    cat = load()
    rows = load_reads()
    return {EDGE: gen_edge(cat), RBAC: gen_rbac(cat), PROBES: gen_probes(cat), DEVJSON: gen_devjson(cat),
            COLL_RBAC: gen_collector_rbac(rows), COLL_PROBES: gen_collector_probes(rows)}


def write(files: dict[str, str], root: str) -> None:
    for rel, text in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)


def check(files: dict[str, str]) -> int:
    """Write into a temp dir and diff against the tree - the same bytes `write` would produce."""
    stale = 0
    with tempfile.TemporaryDirectory(prefix="ops-wiring-") as tmp:
        write(files, tmp)
        for rel in OUTPUTS:
            want = open(os.path.join(tmp, rel), encoding="utf-8").read()
            try:
                have = open(os.path.join(ROOT, rel), encoding="utf-8").read()
            except OSError:
                have = ""
            if want != have:
                stale += 1
                print(f"STALE  {rel}")
                sys.stdout.writelines(list(difflib.unified_diff(
                    have.splitlines(True), want.splitlines(True), f"a/{rel}", f"b/{rel}"))[:80])
            else:
                print(f"ok     {rel}")
    if stale:
        print(f"\n{stale} generated file(s) out of date - run `just ops-wiring` and commit the result.")
    return 1 if stale else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--check", action="store_true", help="fail if a generated file is stale")
    ap.add_argument("--out", help="write under this directory instead of the repository")
    args = ap.parse_args()
    try:
        files = render()
    except guard.CatalogError as e:
        print(f"catalog.toml is invalid: {e}", file=sys.stderr)
        return 2
    except ReadsError as e:
        print(f"{READS} is invalid: {e}", file=sys.stderr)
        return 2
    if args.check:
        return check(files)
    write(files, args.out or ROOT)
    for rel in OUTPUTS:
        print(f"wrote  {os.path.join(args.out, rel) if args.out else rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
