#!/usr/bin/env python3
"""Rewrite the portability baseline, keeping the reasoning attached to each entry.

Called only by `portability.sh --update`. It exists as its own file rather than a
heredoc because it is a merge, not a print, and a forty-line heredoc inside a
shell script is where quoting bugs go to live.

WHY IT IS A MERGE AT ALL. The first version regenerated the baseline from
scratch, and on its second real use it silently ate a seven-line note explaining
why `apps/portal-next/checks/repo-roots.mjs` holds 18 home-path hits ON PURPOSE -
every one a fictional machine (`/home/ada`, `/opt/bothy`), because that file
exists to prove Bothy runs on a checkout that is NOT this one.

That note is the only thing standing between a future reader and "fixing" a
portability problem that is really a test fixture. A tool that throws away the
argument for the thing it is recording is worse than one that refuses to run: the
entry survives looking unjustified, and the reasoning is gone.

A comment block belongs to the entry it PRECEDES - which is how they are written
in the file - so it travels with that entry: re-emitted when the entry survives,
dropped when the entry does.
"""
import os
import sys

HEADER = [
    "# Accepted portability hits. Generated by scripts/checks/portability.sh --update.",
    "#",
    "# Every line here is a reason someone else cannot run this repository.",
    "# The list should only ever get SHORTER. If you are adding to it, you are",
    "# adding a reason - say why in the commit message.",
    "#",
    "# file<TAB>kind<TAB>count",
]

path = sys.argv[1]
now = [l for l in os.environ.get("NOW", "").split("\n") if l.strip()]


def key(line):
    """(file, kind) - the identity of an entry. The COUNT is expected to change."""
    return tuple(line.split("\t")[:2])


# ── read the old file as (comment block, entry) pairs ───────────────────────
pairs, block, seen_first = [], [], False
try:
    with open(path, encoding="utf-8") as fh:
        for line in fh.read().split("\n"):
            if line.startswith("#"):
                block.append(line)
            elif line.strip():
                pairs.append((block, line))
                block, seen_first = [], True
            else:
                # A blank line ends a block: a comment separated from an entry by
                # whitespace is a section note, not that entry's reason.
                block = []
except FileNotFoundError:
    pass

# THE HEADER AND THE FIRST ENTRY'S REASONING ARE ONE BLOCK - there is no blank
# line between them, so a naive "drop the leading block" throws away the first
# entry's argument along with the boilerplate. That is exactly what happened: the
# repo-roots.mjs note is the first entry's, and it vanished twice before this.
#
# The header ends at its last line, which is a fixed string. Anything after that
# inside the same block belongs to the entry.
if pairs:
    first_block = pairs[0][0]
    if HEADER[-1] in first_block:
        cut = first_block.index(HEADER[-1]) + 1
        pairs[0] = (first_block[cut:], pairs[0][1])
    else:
        pairs[0] = ([], pairs[0][1])

current = {key(l): l for l in now}

out, emitted = list(HEADER), set()
for blk, entry in pairs:
    k = key(entry)
    if k in current:
        out.extend(blk)
        out.append(current[k])          # take the NEW count
        emitted.add(k)
    # else: the entry is gone, and its reasoning goes with it

for line in now:
    if key(line) not in emitted:
        out.append(line)                # newly accepted, no reasoning yet

with open(path, "w", encoding="utf-8") as fh:
    fh.write("\n".join(out) + "\n")
